# Generated by Django 2.2.6 on 2019-10-12 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0004_auto_20191011_2025'),
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainees_health_issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heald', models.BooleanField(default=False)),
                ('issue_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='health_app.Issues')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trainees.Trainees')),
            ],
        ),
        migrations.CreateModel(
            name='Trainees_health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='health_app.Issues')),
                ('trainee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='trainees.Trainees')),
            ],
        ),
        migrations.CreateModel(
            name='Solution_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='health_app.Issues')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='health_app.Solutions')),
            ],
        ),
    ]
