# Generated by Django 2.2.6 on 2019-10-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_solution_list_trainees_health_trainees_health_issues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainees_health_issues',
            old_name='heald',
            new_name='healed',
        ),
        migrations.DeleteModel(
            name='Trainees_health',
        ),
    ]
