# Generated by Django 2.2.6 on 2019-10-12 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_auto_20191012_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution_list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
