# Generated by Django 2.2.6 on 2019-10-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0004_solution_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution_list',
            name='date',
        ),
    ]
