# Generated by Django 2.2.6 on 2019-10-12 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0005_remove_solution_list_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution_list',
            old_name='is_valid',
            new_name='valid',
        ),
        migrations.AddField(
            model_name='solution_list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
