# Generated by Django 2.2.6 on 2019-10-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0006_auto_20191012_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution_list',
            old_name='valid',
            new_name='is_valid',
        ),
        migrations.RemoveField(
            model_name='solution_list',
            name='date',
        ),
    ]
