# Generated by Django 2.2.6 on 2019-10-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0007_auto_20191012_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='issues',
            field=models.ManyToManyField(to='health_app.Issues'),
        ),
    ]
