# Generated by Django 2.2.6 on 2019-10-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0008_solutions_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='issues',
            field=models.ManyToManyField(default=None, to='health_app.Issues'),
        ),
    ]
