# Generated by Django 2.2.6 on 2019-10-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0009_auto_20191018_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutions',
            name='issues',
        ),
    ]
