# Generated by Django 2.2.6 on 2019-10-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0012_remove_solutions_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution_list',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
