# Generated by Django 2.2.6 on 2019-10-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0013_auto_20191024_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='solve_ability',
            field=models.BooleanField(default=True),
        ),
    ]
