# Generated by Django 2.2.6 on 2019-10-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(help_text='your phone', max_length=20),
        ),
    ]
