# Generated by Django 2.2.6 on 2019-10-07 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0002_auto_20191007_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='your phone', max_length=20)),
                ('roll_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('age', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('shape', models.BooleanField(default=True)),
                ('health_issue', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trainers.Trainer')),
            ],
        ),
    ]
