# Generated by Django 2.2.6 on 2019-10-20 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0004_auto_20191011_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physical_attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('push_ups', models.IntegerField(blank=True)),
                ('pull_ups', models.IntegerField(blank=True)),
                ('dips', models.IntegerField(blank=True)),
                ('handstand', models.DecimalField(blank=True, decimal_places=4, max_digits=6)),
                ('muscle_up', models.IntegerField(blank=True)),
                ('deadlifts', models.IntegerField(blank=True)),
                ('squat', models.IntegerField(blank=True)),
                ('bench_press', models.IntegerField(blank=True)),
                ('run', models.DecimalField(blank=True, decimal_places=4, max_digits=6)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trainees.Trainees')),
            ],
        ),
    ]
