# Generated by Django 2.2.6 on 2019-10-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0006_auto_20191020_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='physical_attribute',
            name='l_set',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8),
        ),
    ]
