# Generated by Django 2.2.7 on 2019-12-10 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0010_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainees',
            name='age',
        ),
        migrations.AddField(
            model_name='trainees',
            name='birthDay',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='trainees',
            name='initialLevel',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('elite', 'elite')], default='beginner', max_length=50),
        ),
    ]
